#  1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [1]:
import numpy as np
arr = np.array([0,1,2,3,4,5])
print(arr.dtype)

int32


# 2. Given a NumPy array 'arr', check if its data type is float64.
#   arr = np.array([1.5, 2.6, 3.7])

In [2]:
#2
arr= np.array([1.5,2.6,3.7])
if (arr.dtype=="float64"):
    print("True")
else:
    print("False")

True


# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
#3
import random as rnd
arr = np.random.randint(1,10,(1,3))
arr =np.array(arr,dtype='complex128')
arr

array([[3.+0.j, 5.+0.j, 5.+0.j]])

# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
#4
arr = np.array([1,2,3,4])
new_arr = arr.astype('float32')
new_arr

array([1., 2., 3., 4.], dtype=float32)

# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [3]:
#5
arr = np.array([1.23456789234, 2.23456789234, 5.23456789234])
print(arr.dtype)
new_arr = arr.astype('float32')
new_arr

float64


array([1.2345679, 2.2345679, 5.234568 ], dtype=float32)

# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type


In [7]:
#6
def array_attributes(arr):
    shape=arr.shape
    size=arr.size
    dataType= arr.dtype
    return (shape,size,dataType)

arr = np.random.randint(1,10,(4,3))
[shape,size,data_type]= array_attributes(arr)
print("Shape of array is "+str(shape))
print("Size of array is "+str(size))
print("Data Type of array is "+str(data_type))

Shape of array is (4, 3)
Size of array is 12
Data Type of array is int32


# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [8]:
#7
def array_dimension(arr):
    dimension=arr.ndim
    return dimension

arr = np.random.randint(1,10,(4,3))
dimension= array_dimension(arr)
print("Dimension of array is "+str(dimension))

Dimension of array is 2


# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.


In [9]:
# 8
def item_size_info(arr):
    size=arr.size
    Bytesize=arr.nbytes
    return (size,Bytesize)

arr = np.random.randint(1,10,(4,3))
[size,ByteSize]= item_size_info(arr)
print("Size of array is "+str(size))
print("Bytes of array is "+str(ByteSize))

Size of array is 12
Bytes of array is 48


# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [10]:
# 9
def array_strides(arr):
    strides=arr.strides
    return strides

arr = np.random.randint(1,10,(4,3))
strides= item_size_info(arr)
print("Strides of array is "+str(strides))

Strides of array is (12, 48)


# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [11]:
# 10
def shape_stride_relationship(arr):
    shape=arr.shape
    strides=arr.strides
    return (shape,strides)

arr = np.random.randint(1,10,(4,3))
[shape,strides]= shape_stride_relationship(arr)
print("Shape of array is "+str(shape))
print("Strides of array is "+str(strides))

Shape of array is (4, 3)
Strides of array is (12, 4)


# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

In [13]:
# 11

def create_zeros_array(n):
    arr = np.zeros((1,n))
    return arr
n = int(input("Enter a number: "))
arr= create_zeros_array(n)
print(arr)

[[0. 0. 0. 0. 0.]]


# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [4]:
# 12

def create_ones_matrix(rows,cols):
    arr = np.ones((rows,cols))
    return arr
arr= create_ones_matrix(4,5)
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

In [21]:
# 13

def generate_range_array(start,stop,step):
    arr = np.arange(start,stop,step)
    return arr
arr= generate_range_array(1,11,2)
print(arr)

[1 3 5 7 9]


# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [26]:
# 14

def generate_linear_space(start,stop,num):
    arr = np.linspace(start,stop,num)
    return arr
arr= generate_linear_space(1.5, 10.5, 7)
print(arr)

[ 1.5  3.   4.5  6.   7.5  9.  10.5]


# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

In [27]:
# 15

def create_identity_matrix(n):
    arr = np.eye(n)
    return arr
arr= create_identity_matrix(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 16. Write a function that takes a Python list and converts it into a NumPy array.

In [30]:
#16

def Convert_Python_List_To_Numpy_Array(pythonList):
    arr = np.array(pythonList)
    return arr

pythonList = [1,2,3,4,5,6,7]
arr = Convert_Python_List_To_Numpy_Array(pythonList)

print("Python List is : ")
print(pythonList)
print("===============================================")
print("Numpy Array is : ")
print(arr)

Python List is : 
[1, 2, 3, 4, 5, 6, 7]
Numpy Array is : 
[1 2 3 4 5 6 7]


# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [35]:
# 17

arr = np.array([1,2,3,4,5])
x= arr.view() # shallow copy
y=arr.copy()  # deep copy

arr[0]= 100
print(arr)
print(x)
print(y)

[100   2   3   4   5]
[100   2   3   4   5]
[1 2 3 4 5]


# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [47]:
# 18
def  concatenation_array(arr1,arr2):
    concatenation_array =np.concatenate((arr1,arr2),axis=1)  # concatenation to the right
    return concatenation_array
arr1 = np.array([[1,2,3,4],[4,7,1,8]])
arr2= np.array([[6,8,9,1],[10,12,6,8]])

concatenation_array = concatenation_array(arr1,arr2)

concatenation_array



array([[ 1,  2,  3,  4,  6,  8,  9,  1],
       [ 4,  7,  1,  8, 10, 12,  6,  8]])

# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

In [51]:
# 19 
arr1 = np.array([[1,2,3,4],[4,7,1,8],[8,3,0,10]])
arr2= np.array([[6,8,9,1],[10,12,6,8]])

concatenation_array =np.concatenate((arr1,arr2),axis=0)  # concatenation to the bottom ...horizontally
concatenation_array

array([[ 1,  2,  3,  4],
       [ 4,  7,  1,  8],
       [ 8,  3,  0, 10],
       [ 6,  8,  9,  1],
       [10, 12,  6,  8]])

# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [54]:
# 20
def vertical_stack_arrays(arr1,arr2):
    vertical_stack= np.vstack((arr1,arr2))
    return vertical_stack

arr1 = np.array([[1,2,3,4],[4,7,1,8],[8,3,0,10]])
arr2= np.array([[6,8,9,1],[10,12,6,8]])
vertical_stack = vertical_stack_arrays(arr1,arr2)
vertical_stack

array([[ 1,  2,  3,  4],
       [ 4,  7,  1,  8],
       [ 8,  3,  0, 10],
       [ 6,  8,  9,  1],
       [10, 12,  6,  8]])

# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
#21
def range_array_inclusive_given_stepSize(START, STOP, STEP):
    arr = np.arange(START, STOP+STEP, STEP)
    print(arr)

# calling the fumction
START = int(input("Enter start value: "))
STOP =  int(input("Enter stop value: "))
STEP = int(input("Enter step value: "))
range_array_inclusive_given_stepSize(START,STOP,STEP)

# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [56]:
#22
def generate_equal_spaced_array_inclusive():
    arr = np.linspace(0,1,10)
    print(arr)

# calling the fumction
generate_equal_spaced_array_inclusive()

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [87]:
#23
def generate_equal_logarithmically_spaced_array_inclusive():
    arr = np.logspace(1,1000,5,endpoint=True)
    print(arr)

# calling the fumction
generate_equal_logarithmically_spaced_array_inclusive()

[1.00000000e+001 5.62341325e+250             inf             inf
             inf]


# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
#24
import numpy as np
import pandas as pd
arr = np.random.randint(1,100,(5,3))
print(arr)

df = pd.DataFrame(arr)
print(df)

# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
# 25

import numpy as np
import pandas as pd
arr = np.random.randint(-10,10,(5,3))

df = pd.DataFrame(arr)
print(df)
df[df<0]=0  # if df data is negative it will be replaced by 0 through out the data frame
print(df)

# 26. Access the 3rd element from the given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])


In [90]:
#26

arr= np.array([10,20,30,40,50])

#accessing 3rd element
arr[2]

30

# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
# arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [100]:
#27

arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(arr_2d)
# retrieve (1,2) index element

arr_2d[1,2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])


In [99]:
# 28
arr = np.array([3,8,2,10,5,7])
dummy=arr>5
dummy
arr[dummy]

array([ 8, 10,  7])

# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
#29
arr= np.arange(1,10)
arr[2:6]

array([3, 4, 5, 6])

# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
# arr_2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

In [102]:
# 30

arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
sliced_2d_array = arr_2d[0:2,1:3]
sliced_2d_array

array([[2, 3],
       [5, 6]])

# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [109]:
# 31
arr_2d = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
indices = np.array([[0],[1]])
arr = arr_2d[indices,indices]
arr

array([[1],
       [5]])

# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [111]:
# 32
def extract_array_greater_than_threshold_value():
    arr = np.array([1,2,3,4,10,20,43,76,41,90,6])
    bool_index = arr>10 # here takes 10 as a threshold value
    print(arr[bool_index])


# function calling
extract_array_greater_than_threshold_value()


[20 43 76 41 90]


# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [112]:
# 33


# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [121]:
# 34

def extract_array_by_statisfying_multiple_condition():
    arr = np.array([1,2,3,4,10,20,43,76,41,90,6,100,121])
    mask1 = arr>10
    mask2 = arr%2 ==0

    ultimate_mask = np.logical_and(mask1,mask2)
    print(arr[ultimate_mask])

extract_array_by_statisfying_multiple_condition()

[ 20  76  90 100]


# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [127]:
#35

arr_2d = np.random.randint(1,100,(4,5))

row_index = np.array([1,3])
col_index = np.array([2,4])
print("actual array")
print(arr_2d)
print("==========================")

sliced_array = arr_2d[row_index[0]:row_index[1],col_index[0]:col_index[1]]
print(sliced_array)


actual array
[[95 11 51 28 41]
 [13 81  8 61 48]
 [25 20 49 68  9]
 [62 37 94 49 80]]
[[ 8 61]
 [49 68]]


# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [131]:
# 36

arr = np.random.randint(1,100,(3,3))
print("actual array")
print(arr)
print("==========================")
arr = arr+5
print("array after addition 5")
print(arr)
print("==========================")


actual array
[[73 89 88]
 [83 65 51]
 [77 29 22]]
array after addition 5
[[78 94 93]
 [88 70 56]
 [82 34 27]]


In [156]:
# 37
arr1 = np.random.randint(1,100,(1,3))
print(arr1)
print("================")
arr2 = np.random.randint(1,100,(3,4))
print(arr2)
print("================")

try:
    result =arr1+arr2
    print(result)
except ValueError as e:
    print(f"ValueError:{e}")

# explanation : in arr1 row count 1 and in arr2 row count 3. this is okay as per broadcasting rule
# but in arr1 col count 3 and in arr2 col count 4. this col count should be same here as per broadcasting rule

[[40 70 90]]
[[72 12 56  4]
 [80 54 38 12]
 [36 93 42 37]]
ValueError:operands could not be broadcast together with shapes (1,3) (3,4) 


# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [155]:
# 38
arr1 = np.random.randint(1,100,(1,4))
print(arr1)
print("================")
arr2 = np.random.randint(1,100,(4,3))
print(arr2)
print("================")

try:
    result =arr1+arr2
    print(result)
except ValueError as e:
    print(f"ValueError:{e}")

# explanation : same explanation as above

[[21 31  3 23]]
[[34 63 29]
 [13 16 88]
 [64 55 33]
 [86 45 51]]
ValueError:operands could not be broadcast together with shapes (1,4) (4,3) 


# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [154]:
#39
arr1 = np.random.randint(1,100,(3,1))
print(arr1)
print("================")
arr2 = np.random.randint(1,100,(1,3))
print(arr2)
print("================")

try:
    result =arr1+arr2
    print(result)
except ValueError as e:
    print(f"ValueError:{e}")

[[31]
 [ 4]
 [68]]
[[10  4 28]]
[[41 35 59]
 [14  8 32]
 [78 72 96]]


# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [153]:
#40

arr1 = np.random.randint(1,100,(2,2))
print(arr1)
print("================")
arr2 = np.random.randint(1,100,(2,3))
print(arr2)
print("================")

try:
    result =arr1+arr2
    print(result)
except ValueError as e:
    print(f"ValueError:{e}")

[[47 83]
 [79 14]]
[[14 80  2]
 [48 22 64]]
ValueError:operands could not be broadcast together with shapes (2,2) (2,3) 


# 41. Calculate column wise mean for the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])


In [159]:
# 41

arr = np.array([[1,2,3],[4,5,6]])
column_wise_mean = arr.mean(axis=0)
column_wise_mean

array([2.5, 3.5, 4.5])

# 42. Find maximum value in each row of the given array:
# arr = np.array([[1, 2, 3], [4, 5, 6]])


In [160]:
# 42

arr = np.array([[1,2,3],[4,5,6]])
max_each_row = arr.max(axis=1)
max_each_row

array([3, 6])

# 43. For the given array, find indices of maximum value in each column
# arr = np.array([[1, 2, 3], [4, 5, 6]])


In [161]:
# 43
arr = np.array([[1,2,3],[4,5,6]])
max_indices_at_each_col = arr.argmax(axis=0)
max_indices_at_each_col

array([1, 1, 1], dtype=int32)

# 44. For the given array, apply custom function to calculate moving sum along rows.
# arr = np.array([[1, 2, 3], [4, 5, 6]])


In [191]:
# 44

arr = np.array([[1,2,3],[4,5,6]])
moving_sum_along_rows = arr.sum(axis=1)
moving_sum_along_rows

array([ 6, 15])

# 45. In the given array, check if all elements in each column are even.
# arr = np.array([[2,4,6],[3,5,7]])

In [190]:
#45
arr = np.array([[2,4,6],[3,5,7]])

col_wise_even_check = np.all(arr%2==0,axis=0)
col_wise_even_check

array([False, False, False])

# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
# original_array = np.array([1, 2, 3, 4, 5, 6])


In [192]:
# 46

original_array = np.array([1,2,3,4,5,6])
reshaped_array = original_array.reshape(2,3)
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

# 47. Create a function that takes a matrix as input and returns the flattened array.
# input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [197]:
# 47
def flatten_matrix(arr):
    return arr.flatten()  # we can use ravel() as well


input_matrix= np.array([[1,2,3],[4,5,6]])
flatten_mat =flatten_matrix(input_matrix)
flatten_mat

array([1, 2, 3, 4, 5, 6])

# 48. Write a function that concatenates two given arrays along a specified axis.
# array1 = np.array([[1, 2], [3, 4]]) 
# array2 = np.array([[5, 6], [7, 8]])


In [200]:
# 48
def concat(arr1,arr2):
    return np.concatenate((arr1,arr2),axis=0)

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

concat_arrays = concat(arr1,arr2)
concat_arrays

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
# original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [203]:
# 49
def split_arrays(original_array):
    return np.split(original_array,[1],axis=1)
    
original_array = np.array([[1,2,3],
                           [4,5,6],
                           [7,8,9]])
split_arr = split_arrays(original_array)
split_arr

[array([[1],
        [4],
        [7]]),
 array([[2, 3],
        [5, 6],
        [8, 9]])]

# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
# original_array = np.array([1, 2, 3, 4, 5])
# indices_to_insert = [2, 4]
# values_to_insert = [10, 11]
# indices_to_delete = [1, 3]

In [209]:
# 50
def insert_delete_into_array(original_array,indices_to_insert,values_to_incert,indices_to_delete):
    arr_after_insert = np.insert(original_array, indices_to_insert, values_to_incert)
    arr_after_delete = np.delete( original_array, indices_to_delete)
    print("Array_after_insert")
    
    print(arr_after_insert)
    print("====================")
    print("Original Array")
    
    print(original_array)
    print("====================")
    print("Array_after_Delete")
   
    print(arr_after_delete)
    print("====================")
   
    print("Original Array")
    
    print(original_array)
    print("====================")
    
original_array = np.array([1,2,3,4,5])
indices_to_insert =[2,4]
values_to_incert =[10,11]
indices_to_delete =[1,3]

insert_delete_into_array(original_array,indices_to_insert,values_to_incert,indices_to_delete)

Array_after_insert
[ 1  2 10  3  4 11  5]
Original Array
[1 2 3 4 5]
Array_after_Delete
[1 3 5]
Original Array
[1 2 3 4 5]


# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [218]:
# 51

arr1 = np.random.randint(100, size=10)
arr2 = np.random.randint(1,10, size=10)
print(arr1)
print(arr2)

result = np.add(arr1,arr2)
result

[42 76 13 84 22 49 31 38 71 73]
[6 6 9 4 3 1 9 3 9 1]


array([48, 82, 22, 88, 25, 50, 40, 41, 80, 74])

# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [222]:
# 52
arr1 = np.arange(10,1,-1)
arr2 = np.arange(1,10)
print(arr1)
print(arr2)
result = np.subtract(arr1,arr2)
result

[10  9  8  7  6  5  4  3  2]
[1 2 3 4 5 6 7 8 9]


array([ 9,  7,  5,  3,  1, -1, -3, -5, -7])

# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`.

In [224]:
# 53
arr1 = np.random.randint(1,100,(3,4))
arr2 = np.random.randint(1,5, (3,4))
print(arr1)
print(arr2)

result = np.multiply(arr1,arr2)
result

[[92 52 77 25]
 [ 1 84 63 61]
 [42 82 83 53]]
[[4 4 1 3]
 [4 1 4 4]
 [2 1 1 2]]


array([[368, 208,  77,  75],
       [  4,  84, 252, 244],
       [ 84,  82,  83, 106]])

# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [225]:
# 54


arr1 = np.arange(2,12,2)
arr2 =  np.arange(1,6)
print(arr1)
print(arr2)

result = np.divide(arr1,arr2)
result


[ 2  4  6  8 10]
[1 2 3 4 5]


array([2., 2., 2., 2., 2.])

# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.


In [238]:
# 55

arr1 =  np.arange(1,6)
arr2 = arr1[::-1]
print(arr1)
print(arr2)

result = np.exp(arr1**arr2)
result

[1 2 3 4 5]
[5 4 3 2 1]


array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
# arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [245]:
# 56 
def occurrence_of_substring_within_numpy_array_string(arr):
    unique, counts = np.unique(arr, return_counts=True)
    print(dict(zip(unique, counts)))

# calling the funcion below
arr = np.array(['hello','world','hello','numpy','hello','world'])
occurrence_of_substring_within_numpy_array_string(arr)


{'hello': 3, 'numpy': 1, 'world': 2}


# 57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [249]:
# 57

def extract_uppercase_character_from_numpy_array_string(arr):
    for element in arr:
        res=[]
        for char in element:
            if ord(char) in range(65,91): # here checking all the chararcter of each word belong
                 res.append(char)         #to corresponding upper case ASCII value 
               
        print(res)

# calling the funcion below
arr = np.array(['World','GPT','Numpy','OpenAI'])
extract_uppercase_character_from_numpy_array_string(arr)

['W']
['G', 'P', 'T']
['N']
['O', 'A', 'I']


# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [250]:
# 58



# 59. Write a function that concatenates strings in a NumPy array element-wise.
# arr1 = np.array(['Hello', 'World'])
# arr2 = np.array(['Open', 'AI'])

In [257]:
# 59

def concat_two_numpy_array_string_element_wise(arr1,arr2):
    try:
        result =np.char.add(arr1,arr2)
        print(result)
    except ValueError as e:
        print(f"ValueError:{e}")
    
        
arr1 = np.array(['Hello','World'])
arr2= np.array(['Open','AI'])
concat_two_numpy_array_string_element_wise(arr1,arr2)


['HelloOpen' 'WorldAI']


# 60. Write a function that finds the length of the longest string in a NumPy array.
# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [273]:
# 60

arr = np.array(['apple', 'banana', 'grape','pineapple'])
print((max(arr, key=len)),len(max(arr, key=len)))


pineapple 9


# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [285]:
# 61

arr = np.random.randint(1,1000, size=100)
print("Original Array",arr)
print("============================")

print("MEAN : ",np.mean(arr))
print("MEDIAN : ",np.median(arr))
print("VARIANCE : ",np.var(arr))
print("STANDARD DEVIATION : ",np.std(arr))

Original Array [867 762 357 491 581 318 407 947 694 916  18 579  47 990 902 275 474 398
 903 841 857 716 854 268 575 407 570 610 979 110 961 741 746 440   5 167
 427 819 259 475 798 153  70 536 372 725  51  43 133 606 789 966 835 554
 295 162 758 737 323 209 511 872 771 572 688 354 510 348 931 222 208 638
 870 510 444 878 368 340 176 401 290 121 729 629 701 613 827 512 694 271
 375 640 766 999 103 861 169 887 708 822]
MEAN :  541.97
MEDIAN :  571.0
VARIANCE :  78060.3491
STANDARD DEVIATION :  279.3928222055821


# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [ ]:
# 62
import pandas as pd
arr = np.random.randint(1,100, size=50)
print("Original Array",arr)
print("============================")

df = pd.DataFtame(arr)
percentile_25 = (df[0].quantile(0.25))
percentile_75 = (df[0].quantile(0.75))

print("25 percentile of data set", percentile_25)
print("75 percentile of data set", percentile_75)

# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [288]:
# 63

arr1 = np.random.randint(1,100, size=20)
arr2 = np.random.randint(1,100, size=20)
print("Original Array 1",arr1)
print("============================")
print("Original Array 2",arr2)
print("============================")
correlation_coeficient = np.corrcoef(arr1,arr2)
correlation_coeficient

Original Array 1 [75 34 45 69 55 73 60 73 79 18 79  7 11 74 37 52 74 73 27 17]
Original Array 2 [73 40 57 28  8 84 21 96 69 80 87 84 65 67 74 40 71 39 48 32]


array([[1.        , 0.08037266],
       [0.08037266, 1.        ]])

# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [297]:
# 64 

arr1 = np.random.randint(1,10, (3,3))
arr2 = np.random.randint(1,10, (3,3))

mat1 = np.matrix(arr1)
mat2 = np.matrix(arr2)

print("Matrix 1 :  ")
print(mat1)
print("Matrix 2 :  ")
print(mat2)

dot_multiply = np.dot(mat1,mat2)
print("Matrix Dot Multiplication: ")
print(dot_multiply)


Matrix 1 :  
[[8 4 1]
 [9 3 3]
 [5 2 8]]
Matrix 2 :  
[[7 2 3]
 [6 5 3]
 [2 2 5]]
Matrix Dot Multiplication: 
[[82 38 41]
 [87 39 51]
 [63 36 61]]


# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [ ]:
# 65

import pandas as pd
arr = np.random.randint(10,1000, size=50)
print("Original Array",arr)
print("============================")

df = pd.DataFrame(arr)
percentile_10 = (df[0].quantile(0.10))
percentile_25 = (df[0].quantile(0.25))
percentile_50 = (df[0].quantile(0.50))
percentile_75 = (df[0].quantile(0.75))
percentile_90 = (df[0].quantile(0.90))


print("10 percentile of data set : ", percentile_10)
print("25 percentile of data set : ", percentile_25)
print("50 percentile of data set That is Median : ", percentile_50)
print("75 percentile of data set : ", percentile_75)
print("90 percentile of data set : ", percentile_90)

# 66. Create a NumPy array of integers and find the index of a specific element.

In [298]:
# 66

arr = np.random.randint(1,20, size=10)
print("Original Array",arr)
print("============================")
item = int(input("enter a number between 1 to 20 : "))
if item in arr:
     if len(np.where(arr==item)[0]) >1:
        print("Index of "+str(item)+" is "+str(np.where(arr==item)[0]))
    else:
        print("Index of "+str(item)+" is "+str(np.where(arr==item)[0][0]))
 
else:
    print(str(item)+" is not present in array")

Original Array [14  2 13  5 10 17  7  5  3 15]


# 67. Generate a random NumPy array and sort it in ascending order.

In [304]:
# 67

arr = np.random.randint(1,20, size=10)
print("Original Array",arr)
print("============================")

sorted_array = np.sort(arr)
print("sorted array",sorted_array)


Original Array [18 15 12  8 17  3  8  9 12 10]
sorted array [ 3  8  8  9 10 12 12 15 17 18]


# 68. Filter elements >20  in the given NumPy array.
# arr = np.array([12, 25, 6, 42, 8, 30])

In [5]:
# 68 

arr = np.array([12, 25, 6, 42, 8, 30])
print("Original Array",arr)
print("============================")

new_arr = np.where(arr>20)
print("Array elements which are greater than 20",arr[new_arr])


Original Array [12 25  6 42  8 30]
Array elements which are greater than 20 [25 42 30]


# 69. Filter elements which are divisible by 3 from a given NumPy array
# arr = np.array([1, 5, 8, 12, 15])

In [6]:
# 69

arr = np.array([1, 5, 8, 12, 15])
print("Original Array",arr)
print("============================")

new_arr = np.where(arr%3==0)
print("Array elements which are divisible by 3 : ",arr[new_arr])

Original Array [ 1  5  8 12 15]
Array elements which are divisible by 3 :  [12 15]


# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
# arr = np.array([10, 20, 30, 40, 50])

In [317]:
# 70

arr = np.array([10,20,30,40,50])
print("Original Array",arr)
print("============================")

mask1 = arr>=20
mask2 = arr<=40

result = np.logical_and(mask1,mask2)
print("Array elements which are >=20 and <= 40  : ",arr[result])

Original Array [10 20 30 40 50]
Array elements which are >=20 and <= 40  :  [20 30 40]


# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
# arr = np.array([1, 2, 3])  

In [328]:
# 71
arr = np.array([1, 2, 3])  
  
# Check the byte order  
print(arr.dtype.byteorder) 


=


# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`
# arr = np.array([1, 2, 3], dtype=np.int32) 

In [329]:
# 72

arr = np.array([1, 2, 3], dtype=np.int32) 
  
print("Original array:")  
print(arr)  
print("Original byte order:", arr.dtype.byteorder)  
  
# Swap the byte order  
swapped_arr = arr.byteswap()  
print("\nArray after byteswap:")  
print(swapped_arr)  
print("New byte order:", swapped_arr.dtype.byteorder)  



Original array:
[1 2 3]
Original byte order: =

Array after byteswap:
[16777216 33554432 50331648]
New byte order: =


# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
# arr = np.array([1, 2, 3], dtype=np.int32) 

In [331]:
# 73
arr = np.array([1, 2, 3], dtype=np.int32) 
  
print("Original array:")  
print(arr)  
print("Original byte order:", arr.dtype.byteorder)  
  
# Swap the byte order  
swapped_arr = arr.byteswap()  

# aapply newbyteorder on swapped_array
swapped_arr_new = swapped_arr.newbyteorder()    
print("\nArray after newbyteorder:")  
print(swapped_arr_new)  
print("Updated byte order Without modify original array:", swapped_arr_new.dtype.byteorder)  



Original array:
[1 2 3]
Original byte order: =

Array after newbyteorder:
[1 2 3]
Updated byte order Without modify original array: >


# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
# array = np.array([1, 2, 3], dtype=np.int32) 

In [7]:
# 74
  
array = np.array([1, 2, 3], dtype=np.int32)  
system_endianness = np.dtype.byteorder
print("Original array:")  
print(array)  
print("Current byte order is which is system endians : ",array.dtype.byteorder)

if system_endianness == '=':  # system endians
    swapped_array = array.byteswap().newbyteorder()  
else:  
    swapped_array = array.newbyteorder()  
  
print("\nArray after swapping byte order:")  
print(swapped_array)  
print("Now byte order is: ",swapped_array.dtype.byteorder)


Original array:
[1 2 3]
Current byte order is which is system endians :  =

Array after swapping byte order:
[16777216 33554432 50331648]
Now byte order is:  >


# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
# array = np.array([1, 2, 3], dtype=np.int32)

In [351]:
# 75

array = np.array([1, 2, 3], dtype=np.int32)   
byte_order = array.dtype.byteorder  

print("Original Byte Order",byte_order)

# Check if byte swapping is necessary  
if byte_order in ('=', '|'):  
    print("Byte swapping is not necessary (native byte order).")  
else:  
    print("Byte swapping is necessary.")  


Original Byte Order =
Byte swapping is not necessary (native byte order).


# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [361]:
# 76

arr1 = np.arange(1,11)
copy_arr = np.copy(arr1)
# modify in copy_arr
copy_arr[1] = 50
print("copy_arr : ", copy_arr)
print("\nOriginal array arr1 : ",arr1)

copy_arr :  [ 1 50  3  4  5  6  7  8  9 10]

Original array arr1 :  [ 1  2  3  4  5  6  7  8  9 10]


# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [369]:
# 77

matrix = np.random.randint(1,20,(3,3))
print("Original Array\n",matrix)
view_slice = matrix[0:2,0:2]
print("Sliced Array before modify\n",view_slice)
view_slice[0][0]=1000
print("Sliced Array after modify\n",view_slice)
print("Original Array after modify in sliced array\n",matrix)

Original Array
 [[10  9 11]
 [14 16 17]
 [16 14  1]]
Sliced Array before modify
 [[10  9]
 [14 16]]
Sliced Array after modify
 [[1000    9]
 [  14   16]]
Original Array after modify in sliced array
 [[1000    9   11]
 [  14   16   17]
 [  16   14    1]]


# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [386]:
# 78

arr_a = np.arange(1,13)
arr_a = arr_a.reshape(4,3)
print("Original Array\n\n",arr_a)
view_b = arr_a[0:2,0:2]
print("\nSliced Array\n\n",view_b)
view_b = view_b+5
print("\nAdd 5 in sliced array\n\n",view_b)
print("\nOriginal Array again after add 5 in sliced array \n",arr_a)

Original Array

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Sliced Array

 [[1 2]
 [4 5]]

Add 5 in sliced array

 [[ 6  7]
 [ 9 10]]

Original Array again after add 5 in sliced array 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [394]:
# 79

orig_array = np.arange(1,9)
orig_array = orig_array.reshape(2,4)
print("Original Array\n\n",orig_array)

# creating a reshaped view
reshaped_view = orig_array.reshape(4,2)
print("\nReshaped View before modify in reshaped array\n",reshaped_view)
reshaped_view[0][0]=12345
print("\nReshaped View after modify in reshaped array\n",reshaped_view)
print("\nOriginal array after modify in reshaped array\n",reshaped_view)


Original Array

 [[1 2 3 4]
 [5 6 7 8]]

Reshaped View before modify in reshaped array
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Reshaped View after modify in reshaped array
 [[12345     2]
 [    3     4]
 [    5     6]
 [    7     8]]

Original array after modify in reshaped array
 [[12345     2]
 [    3     4]
 [    5     6]
 [    7     8]]


# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [407]:
# 80

data = np.random.randint(1,50,(3,4))
print("Original Array\n",data)

data_copy_mask = data>5
data_copy = data[data_copy_mask]
data_copy = data_copy.reshape(3,4)
print("Extracted Array greater than 5\n",data_copy)
data_copy[0][0]=1000
print("After modify in data_copy\n",data_copy)
print("After modify original array\n",data)

Original Array
 [[ 7 48 20 24]
 [38 38 16 16]
 [48 46 18 39]]
Extracted Array greater than 5
 [[ 7 48 20 24]
 [38 38 16 16]
 [48 46 18 39]]
After modify in data_copy
 [[1000   48   20   24]
 [  38   38   16   16]
 [  48   46   18   39]]
After modify original array
 [[ 7 48 20 24]
 [38 38 16 16]
 [48 46 18 39]]


# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [10]:
# 81

arr1 = np.random.randint(1,50,(3,4))
arr2 = np.random.randint(1,50,(3,4))

A = np.matrix(arr1)
B = np.matrix(arr2)
print("Matrix 1\n",A)
print("Matrix 2\n",B)
add = A + B
sub = A - B

print("Addition of these two matrix\n",add)
print("Subtraction of these two matrix\n",sub)

Matrix 1
 [[35  9 39 16]
 [30 10 39 46]
 [21 37 26 48]]
Matrix 2
 [[ 4 42 44 46]
 [17 42 19 40]
 [33 47 20  8]]
Addition of these two matrix
 [[39 51 83 62]
 [47 52 58 86]
 [54 84 46 56]]
Subtraction of these two matrix
 [[ 31 -33  -5 -30]
 [ 13 -32  20   6]
 [-12 -10   6  40]]


# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [11]:
# 82

arr1 = np.random.randint(1,20,(3,2))
arr2 = np.random.randint(1,20,(2,4))

C = np.matrix(arr1)
D = np.matrix(arr2)
print("Matrix 1\n",C)
print("Matrix 2\n",D)

multiply = C @ D
print("Subtraction of these two matrix\n",multiply)

Matrix 1
 [[ 3 16]
 [ 2 13]
 [16 14]]
Matrix 2
 [[ 5  7 14  4]
 [ 8 13  3 14]]
Subtraction of these two matrix
 [[143 229  90 236]
 [114 183  67 190]
 [192 294 266 260]]


# 83. Create a matrix `E` and find its transpose.

In [13]:
# 83

arr1 = np.random.randint(1,20,(3,2))
E = np.matrix(arr1)
print("Matrix \n",E)
transpose = E.T
print("Transpose of matrix\n",transpose)

Matrix 
 [[ 2  2]
 [ 8 14]
 [14  1]]
Transpose of matrix
 [[ 2  8 14]
 [ 2 14  1]]


# 84. Generate a square matrix `F` and compute its determinant.

In [14]:
# 84

arr1 = np.random.randint(1,20,(3,3))
F = np.matrix(arr1)
print("Matrix \n",F)
determinant = np.linalg.det(F)
print("Determinant of matrix\n",determinant)

Matrix 
 [[ 4  4 12]
 [ 8 12 16]
 [ 9  9 14]]
Determinant of matrix
 -207.99999999999997


# 85. Create a square matrix `G` and find its inverse.

In [15]:
# 85

arr1 = np.random.randint(30,50,(3,3))
G = np.matrix(arr1)
print("Matrix\n",G)
inverse = np.linalg.inv(G)
print("Inverse of matrix\n",inverse)

Matrix
 [[37 37 49]
 [35 39 39]
 [35 30 42]]
Inverse of matrix
 [[-0.23353293  0.04191617  0.23353293]
 [ 0.05239521  0.08033932 -0.13572854]
 [ 0.15718563 -0.09231537 -0.0738523 ]]
